# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-06 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_and_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='old note'),
            preserve_default=False,
        ),
    ]
