# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-11 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_and_authors_app', '0002_authors_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
